### ISSUE TITLE
Support for separate `import`s?

### ISSUE THREAD

**Issue by pcarrier** [Aaronepower/tokei#128]
In Go, Java & Kotlin, import statements aren't exactly what I'd consider code.
For example I would treat a change removing 20 lines of code and adding 25 lines of import as reducing the amount of code.

Being able to treat `import`s separately, like `tokei` does comments, would be a very welcome feature, whether optional or not.

**Comment by Aaronepower** [comment]
Thanks for filing the issue! While you might not consider import statements code others like myself would. If I were to add this feature I couldn't just do Go, Java, and Kotlin. I'd have to add them for every language and some languages have multi line imports which would have to be handled correctly. Overall I would think this problem is out of the scope of tokei.

I would recommend as a simple solution to run tokei on codebase, run `rg 'import' | wc -l` and take the difference.
