### ISSUE TITLE
Compare/Contrast to cloc

### ISSUE THREAD

**Issue by djui** [Aaronepower/tokei#175]
Would be nice to the a should comparison to `cloc` in the readme, mostly for compatibility reasons.

**Comment by Aaronepower** [comment]
Thank you for this issue! I'm not really a cloc power user so I'm not even sure which features overlap. Speed wise I recently compared counting the Firefox 58 source using hyperfine and `tokei .` took on average 6.5 seconds whereas `cloc --skip-uniqueness .` took 2.5 minutes.

**Comment by djui** [comment]
For the comparison I’m less interested in performance but more in algorithm: how are lines detected and counted.

I ran `cloc` and `tokei` on a couple of repositories and came up with very different numbers across languages. Getting different numbers can creation confusion which in turn can lead to disbelief that the performance is sacrificing correctness.

To be fair, since (I assume) neither command ever defines a spec for what/how to count either could be wrong. Maybe it’s possible to take a relatively medium sized, static project and run numbers on it and define this then as a reference for correct/desired line number benchmark.

**Comment by Aaronepower** [comment]
@djui Okay, I can speak as to why they will probably always be different results.

- `tokei` doesn't do any uniqueness check of a file. In my opinion any duplication is an intentional choice on the user's part.

- `tokei` respects your `.gitignore` and won't count anything listed in that(including directories and their children).`cloc` can achieve similar results with `cloc --vcs=git` if you're working in a clean directory, but if you are currently working in a project and haven't added those files to git cloc won't count them with `--vcs`.

- While it might seem that `tokei` must be somewhere sacrifing correctness over performance, `tokei` is actually more accurate and covers cases `cloc` does not. Looking at `cloc`'s [limitations section](https://github.com/AlDanial/cloc#Limitations) we can see that cloc will count comments in string literals as comments. `tokei` will count those as code.

- `cloc` for counting uses regular expressions, whereas `tokei` is just a small state machine that moves linearly through the file. You can actually see how `tokei` counts a file with `tokei -vvv ./file` I recommend only using it on small files as it is a lot of information.

**Comment by djui** [comment]
I think these are great points that would fit into a/the comparison section. Having different numbers and then checking with the compoarsiin section will explain a user of the difference is to be expected or not.

**Comment by mssun** [comment]
The result of `cloc` and `tokei` are not consistent (huge difference). I am counting the LOC of `sh` in FreeBSD. I don't why the results are very different (13181 vs 1813).

```
$ cloc freebsd/bin/sh
     583 text files.
     572 unique files.
     513 files ignored.

http://cloc.sourceforge.net v 1.60  T=1.20 s (58.2 files/s, 15408.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                               26           1564           2232          11727
make                            10             59             19            567
C/C++ Header                    24            139            916            561
Bourne Shell                     9             48            313            284
Teamcenter def                   1              3             51             42
-------------------------------------------------------------------------------
SUM:                            70           1813           3531          13181
-------------------------------------------------------------------------------
```

```
$ tokei freebsd/bin/sh
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
 C                      26        15523        11841         2118         1564
 C Header               24         1616          561          916          139
 Makefile               10          645          567           19           59
 Module-Definition       1           96           93            0            3
 Shell                   9          645          276          321           48
-------------------------------------------------------------------------------
 Total                  70        18525        13338         3374         1813
-------------------------------------------------------------------------------
```

Here are the version info:
```
$ cloc --version
1.60
$ tokei --version
tokei 7.0.1
```

**Comment by Aaronepower** [comment]
A [COMPARISON.md](https://github.com/Aaronepower/tokei/blob/master/COMPARISON.md) is now available.

**Comment by memark** [comment]
> A [COMPARISON.md](https://github.com/Aaronepower/tokei/blob/master/COMPARISON.md) is now available.

A few years later, this file appears to have disappeared. I tried searching, but no luck. Is the information available somewhere else now? @XAMPPRocky

**Comment by XAMPPRocky** [comment]
Thank you for your question, no it isn't because it's out of date, and I'm not interested in maintaining it.

**Comment by memark** [comment]
Thanks, good to know!
