### ISSUE TITLE
Dependency files mistaken for D lang

### ISSUE THREAD

**Issue by petevine** [Aaronepower/tokei#22]
GCC's dependency `.d` files left over from a build are treated as D lang source files. 

Recommend `make clean` somewhere?

**Comment by petevine** [comment]
I wonder about a D project containing dependency files though :)

**Comment by Aaronepower** [comment]
@petevine you should probably just ignore the folder that contains them as you probably don't want to count files generated by and for the compiler, like in Rust just `--exclude target`. However I'm currently considering the addition of a `.tokeirc` which will allow you to overwrite some contentious file extensions, and I might include .d as one.

**Comment by Michael-F-Bryan** [comment]
With this issue, are there any mime-type guessing libraries available in Rust? Therefore allowing you to skip all `*.d` files if they're compiled binaries instead of actual D code.

For example I know in Python there's a library called [python-magic][1] which is a thin wrapper around the `magic` library written in C. Apparently this is actually what linux uses to try and guess the type of a file from its contents when you use the `file` command.

[1]: https://github.com/ahupp/python-magic

**Comment by Aaronepower** [comment]
@Michael-F-Bryan I don't know of any, and I would be reticent to use this specific library as it seems to be *NIX only, and tokei supports Windows, macOS, and Linux(_to a certain extent_).
