### ISSUE TITLE
Split count of lines for code from lines for tests

### ISSUE THREAD

**Issue by Ekleog** [Aaronepower/tokei#248]
Feature idea: have a different counter for main-code lines, and test-code lines.

This would potentially be possible for Rust by counting the lines in tests/ directory and #[cfg(test)] elements… if it's possible to parse these with reasonable accuracy. I'm not sure how it could be handled for other languages, but at worse it could just output “unsupported” in the test column. :)

What do you think about this feature? I believe the amount of test lines is as important as the amount of comment lines, and thus conflating them with code lines appears sad to me, even though the fix would likely be quite hard to pull up. :)

Anyway, thank you for tokei!

**Comment by Aaronepower** [comment]
Thank you for this issue! I think for this you'd really want a Rust specific code counter as there is no way for tokei to figure out the difference without essentially having a whole seperate counter for Rust, which at point could be a seperate application. 😃

Tokei could be used in this application since tokei now exports a language's features in `LanguageType`, but this is out of the scope for tokei itself.
